 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
           fingerprints:
             - "8a:96:7c:4c:8b:0c:09:0f:e0:dc:80:e1:99:a4:b5:96"
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "pwd"
 workflows:
   version: 2
   build-and-deploy:
     jobs:
      # - build
       - deploy:
           requires:
            # - build # only deploy once build job has completed
           
