version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:fa:51:2b:97:31:d6:5e:04:5b:6f:9d:c9:1e:47:85"
      - run:
        -nam: Comando ssh
        command:
          ssh $SSH_USER@$SSH_HOST "pwd"
        
